#!/usr/bin/env python3
"""Test LLM generating multiple tool calls in ADK"""

import asyncio
from google.adk.agents import LlmAgent
from google.adk.sessions import Session
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events import Event
from google.adk.tools import FunctionTool


# Mock MCP toolset
class MockMCPToolset:
    """Mock MCP toolset for testing"""
    
    def get_tools(self):
        """Return list of available tools"""
        return [
            FunctionTool(
                name="mcp__desktop-commander__create_directory",
                function=self.create_directory,
                description="Create a directory"
            ),
            FunctionTool(
                name="mcp__desktop-commander__write_file",
                function=self.write_file,
                description="Write content to a file"
            )
        ]
    
    def create_directory(self, path: str):
        """Mock create directory"""
        print(f"🗂️  TOOL CALLED: create_directory(path='{path}')")
        return {"status": "success", "message": f"Created directory: {path}"}
    
    def write_file(self, path: str, content: str, mode: str = "rewrite"):
        """Mock write file"""
        print(f"📝 TOOL CALLED: write_file(path='{path}', content={len(content)} chars, mode='{mode}')")
        return {"status": "success", "message": f"Wrote file: {path}"}


async def main():
    print("🧪 TESTING LLM-GENERATED MULTIPLE TOOL CALLS IN ADK")
    print("=" * 60)
    
    # Create mock toolset
    mock_toolset = MockMCPToolset()
    
    # Create test agent with explicit instruction to make multiple tool calls
    test_agent = LlmAgent(
        model=get_llm_model(config.CHIEF_RESEARCHER_MODEL),
        name="MultiToolTestAgent",
        instruction="""You are a test agent. When asked to create files, you MUST:
1. First create the directory using create_directory tool
2. Then write the file using write_file tool
IMPORTANT: Make BOTH tool calls in a SINGLE response, not in separate responses.""",
        tools=[mock_toolset],
        output_key="test_result"
    )
    
    # Create session
    session = Session(
        id="test-session",
        appName="test-app", 
        userId="test-user"
    )
    
    # Create context with a request that should trigger multiple tool calls
    ctx = InvocationContext(
        session=session,
        agent=test_agent
    )
    ctx.input_text = "Please create the directory '/tmp/test_multi_tools' and then write a file '/tmp/test_multi_tools/test.txt' with content 'Hello from multiple tools test'. Remember to make BOTH tool calls in ONE response."
    
    print(f"📝 Input: {ctx.input_text}")
    print("=" * 60)
    
    # Track tool calls
    tool_calls = []
    events_count = 0
    
    try:
        # Run the agent
        async for event in test_agent.run_async(ctx):
            events_count += 1
            
            if event.author == "MultiToolTestAgent" and event.content and event.content.parts:
                for part in event.content.parts:
                    if part.function_call:
                        tool_calls.append(part.function_call.name)
                        print(f"🔧 Event {event.id}: Found tool call: {part.function_call.name}")
                    if part.text:
                        print(f"💬 {event.author}: {part.text.strip()}")
            
            # Debug: print all events
            print(f"📊 Event {events_count} - Author: {event.author}, Type: {type(event)}")
    
    except Exception as e:
        print(f"❌ Error during execution: {e}")
        import traceback
        traceback.print_exc()
    
    print("=" * 60)
    print(f"📊 Summary:")
    print(f"   Total events: {events_count}")
    print(f"   Tool calls found: {len(tool_calls)}")
    print(f"   Tools: {tool_calls}")
    
    if len(tool_calls) >= 2:
        print("✅ SUCCESS: Multiple tool calls were generated by LLM!")
    else:
        print("❌ ISSUE: LLM did not generate multiple tool calls")
        print("💡 This confirms the issue - the LLM is not making multiple tool calls in one response")


if __name__ == "__main__":
    # Fix import path
    import sys
    import os
    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    
    asyncio.run(main())